[global]
developmentMode = false
showWarningOnDirectExecution = false

[server]
runOnSave = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true
allowRunOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
# Enhanced Healthcare Theme
primaryColor = "
#2E86AB"
backgroundColor = "
#FFFFFF"
secondaryBackgroundColor = "
#F9FAFB"
textColor = "
#1F2937"
font = "sans serif"

[client]
caching = true
displayEnabled = true
showErrorDetails = false
toolbarMode = "minimal"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance optimizations
[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false

# Security settings
[mapbox]
token = ""

# UI enhancements
[ui]
hideTopBar = false
hideSidebarNav = false
